{
//=========Macro generated from canvas: c1/c1
//=========  (Fri Nov  9 14:57:15 2012) by ROOT version5.34/02
   TCanvas *c1 = new TCanvas("c1", "c1",10,44,600,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   c1->Range(-0.3207368,-1604.363,1.921368,3743.513);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetLeftMargin(0.16);
   c1->SetRightMargin(0.08);
   c1->SetTopMargin(0.06);
   c1->SetBottomMargin(0.3);
   c1->SetFrameBorderMode(0);
   c1->SetFrameBorderMode(0);
   
   TH1F *Graph_hist = new TH1F("Graph_hist","",20,0.038,1.742);
   Graph_hist->SetBinContent(2,113.63);
   Graph_hist->SetBinContent(5,370.85);
   Graph_hist->SetBinContent(19,2632.8);
   Graph_hist->SetBinError(2,35.77545);
   Graph_hist->SetBinError(5,76.09241);
   Graph_hist->SetBinError(19,500.9234);
   Graph_hist->SetMaximum(3422.64);
   Graph_hist->SetEntries(3);
   Graph_hist->SetDirectory(0);
   Graph_hist->SetStats(0);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#ffff00");
   Graph_hist->SetFillColor(ci);
   Graph_hist->SetLineWidth(2);
   Graph_hist->SetMarkerStyle(25);
   Graph_hist->SetMarkerSize(1.2);
   Graph_hist->GetXaxis()->SetTitle("Converter thickness (% rad. len.)");
   Graph_hist->GetXaxis()->SetLabelFont(42);
   Graph_hist->GetXaxis()->SetLabelSize(0);
   Graph_hist->GetXaxis()->SetTitleSize(0.05);
   Graph_hist->GetXaxis()->SetTitleOffset(1.2);
   Graph_hist->GetXaxis()->SetTitleFont(42);
   Graph_hist->GetYaxis()->SetTitle("Events /90nC");
   Graph_hist->GetYaxis()->SetLabelFont(42);
   Graph_hist->GetYaxis()->SetLabelSize(0.05);
   Graph_hist->GetYaxis()->SetTitleSize(0.05);
   Graph_hist->GetYaxis()->SetTitleOffset(1.6);
   Graph_hist->GetYaxis()->SetTitleFont(42);
   Graph_hist->GetZaxis()->SetLabelFont(42);
   Graph_hist->GetZaxis()->SetLabelSize(0.05);
   Graph_hist->GetZaxis()->SetTitleSize(0.05);
   Graph_hist->GetZaxis()->SetTitleFont(42);
   Graph_hist->Draw("hist");
   
   TH1F *Graph_hist = new TH1F("Graph_hist","",20,0.038,1.742);
   Graph_hist->SetBinContent(2,113.63);
   Graph_hist->SetBinContent(5,370.85);
   Graph_hist->SetBinContent(19,2632.8);
   Graph_hist->SetBinError(2,35.77545);
   Graph_hist->SetBinError(5,76.09241);
   Graph_hist->SetBinError(19,500.9234);
   Graph_hist->SetEntries(3);
   Graph_hist->SetStats(0);
   Graph_hist->SetFillColor(2);
   Graph_hist->SetFillStyle(3004);
   Graph_hist->SetMarkerStyle(25);
   Graph_hist->SetMarkerSize(0.0001);
   Graph_hist->GetXaxis()->SetTitle("Converter thickness (% rad. len.)");
   Graph_hist->GetXaxis()->SetLabelFont(42);
   Graph_hist->GetXaxis()->SetLabelSize(0.05);
   Graph_hist->GetXaxis()->SetTitleSize(0.05);
   Graph_hist->GetXaxis()->SetTitleOffset(1.2);
   Graph_hist->GetXaxis()->SetTitleFont(42);
   Graph_hist->GetYaxis()->SetTitle("Events /90nC");
   Graph_hist->GetYaxis()->SetLabelFont(42);
   Graph_hist->GetYaxis()->SetLabelSize(0.05);
   Graph_hist->GetYaxis()->SetTitleSize(0.05);
   Graph_hist->GetYaxis()->SetTitleOffset(1.6);
   Graph_hist->GetYaxis()->SetTitleFont(42);
   Graph_hist->GetZaxis()->SetLabelFont(42);
   Graph_hist->GetZaxis()->SetLabelSize(0.05);
   Graph_hist->GetZaxis()->SetTitleSize(0.05);
   Graph_hist->GetZaxis()->SetTitleFont(42);
   Graph_hist->Draw("E2,same");
   
   TH1F *Graph_hist = new TH1F("Graph_hist","",20,0.038,1.742);
   Graph_hist->SetBinContent(2,92.10506);
   Graph_hist->SetBinContent(5,196.4422);
   Graph_hist->SetBinContent(19,1063.679);
   Graph_hist->SetBinError(2,0.558971);
   Graph_hist->SetBinError(5,0.658302);
   Graph_hist->SetBinError(19,2.324042);
   Graph_hist->SetMaximum(3422.64);
   Graph_hist->SetEntries(3);
   Graph_hist->SetDirectory(0);
   Graph_hist->SetStats(0);
   Graph_hist->SetLineWidth(2);
   Graph_hist->SetMarkerStyle(20);
   Graph_hist->SetMarkerSize(1.2);
   Graph_hist->GetXaxis()->SetTitle("Converter thickness (% rad. len.)");
   Graph_hist->GetXaxis()->SetLabelFont(42);
   Graph_hist->GetXaxis()->SetLabelSize(0);
   Graph_hist->GetXaxis()->SetTitleSize(0.05);
   Graph_hist->GetXaxis()->SetTitleOffset(1.2);
   Graph_hist->GetXaxis()->SetTitleFont(42);
   Graph_hist->GetYaxis()->SetTitle("Events /90nC");
   Graph_hist->GetYaxis()->SetLabelFont(42);
   Graph_hist->GetYaxis()->SetLabelSize(0.05);
   Graph_hist->GetYaxis()->SetTitleSize(0.05);
   Graph_hist->GetYaxis()->SetTitleOffset(1.6);
   Graph_hist->GetYaxis()->SetTitleFont(42);
   Graph_hist->GetZaxis()->SetLabelFont(42);
   Graph_hist->GetZaxis()->SetLabelSize(0.05);
   Graph_hist->GetZaxis()->SetTitleSize(0.05);
   Graph_hist->GetZaxis()->SetTitleFont(42);
   Graph_hist->Draw("elpsame");
  
// ------------>Primitives in pad: p_test
   TPad *p_test = new TPad("p_test", "",0,0,1,1);
   p_test->Draw();
   p_test->cd();
   p_test->Range(-0.3207368,-0.4999998,1.921368,6.166665);
   p_test->SetFillColor(0);
   p_test->SetFillStyle(4000);
   p_test->SetBorderMode(0);
   p_test->SetBorderSize(0);
   p_test->SetGridy();
   p_test->SetTickx(1);
   p_test->SetTicky(1);
   p_test->SetLeftMargin(0.16);
   p_test->SetRightMargin(0.08);
   p_test->SetTopMargin(0.7);
   p_test->SetBottomMargin(0.15);
   p_test->SetFrameBorderMode(0);
   p_test->SetFrameBorderMode(0);
   
   TH1F *Graph_hist_ratio = new TH1F("Graph_hist_ratio","",20,0.038,1.742);
   Graph_hist_ratio->SetBinContent(2,0.8105699);
   Graph_hist_ratio->SetBinContent(5,0.5297078);
   Graph_hist_ratio->SetBinContent(19,0.4040104);
   Graph_hist_ratio->SetBinError(2,0.2552485);
   Graph_hist_ratio->SetBinError(5,0.108702);
   Graph_hist_ratio->SetBinError(19,0.07687314);
   Graph_hist_ratio->SetMinimum(0.5);
   Graph_hist_ratio->SetMaximum(1.5);
   Graph_hist_ratio->SetEntries(36.71135);
   Graph_hist_ratio->SetDirectory(0);
   Graph_hist_ratio->SetStats(0);
   Graph_hist_ratio->SetLineWidth(2);
   Graph_hist_ratio->SetMarkerStyle(20);
   Graph_hist_ratio->SetMarkerSize(1.2);
   Graph_hist_ratio->GetXaxis()->SetTitle("Converter thickness (% rad. len.)");
   Graph_hist_ratio->GetXaxis()->SetLabelFont(42);
   Graph_hist_ratio->GetXaxis()->SetLabelSize(0.05);
   Graph_hist_ratio->GetXaxis()->SetTitleSize(0.05);
   Graph_hist_ratio->GetXaxis()->SetTitleOffset(1.2);
   Graph_hist_ratio->GetXaxis()->SetTitleFont(42);
   Graph_hist_ratio->GetYaxis()->SetTitle("Ratio");
   Graph_hist_ratio->GetYaxis()->SetNdivisions(509);
   Graph_hist_ratio->GetYaxis()->SetLabelFont(42);
   Graph_hist_ratio->GetYaxis()->SetLabelSize(0.025);
   Graph_hist_ratio->GetYaxis()->SetTitleSize(0.05);
   Graph_hist_ratio->GetYaxis()->SetTitleOffset(1.3);
   Graph_hist_ratio->GetYaxis()->SetTitleFont(42);
   Graph_hist_ratio->GetZaxis()->SetLabelFont(42);
   Graph_hist_ratio->GetZaxis()->SetLabelSize(0.05);
   Graph_hist_ratio->GetZaxis()->SetTitleSize(0.05);
   Graph_hist_ratio->GetZaxis()->SetTitleFont(42);
   Graph_hist_ratio->Draw("elp");
   TLatex *   tex = new TLatex(0.2093229,0.9136123," ");
tex->SetNDC();
   tex->SetTextFont(42);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TLegend *leg = new TLegend(0.2587937,0.5850785,0.5098873,0.8162304,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(19);
   leg->SetFillStyle(0);
   TLegendEntry *entry=leg->AddEntry("Graph_hist","Geant4","f");

   ci = TColor::GetColor("#ffff00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextAlign(12);
   entry->SetTextColor(1);
   entry=leg->AddEntry("Graph_hist","Data","elp");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1.2);
   entry->SetTextAlign(12);
   entry->SetTextColor(1);
   leg->Draw();
   p_test->Modified();
   c1->cd();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
